// Value-only allowlist for the main-window preload. Kept in a tiny sibling
// module so bundle-external parity tests can import it without Electron deps.
export const MAIN_COMMANDS = [
  "health",
  "get_app_model",
  "get_app_settings",
  "save_app_settings",
  "list_microphone_devices",
  "list_permission_statuses",
  "open_permission_settings",
  "request_permission_authorization",
  "is_accessibility_trusted",
  "request_accessibility_permission",
  "save_mode",
  "create_mode",
  "delete_mode",
  "delete_history_record",
  "clear_history",
  "confirm_dialog",
  "save_dictionary_entry",
  "delete_dictionary_entry",
  "cancel_active_voice_runtime",
  "finish_active_voice_runtime",
  "save_provider_config",
  "test_provider_config",
  "delete_provider_config",
  "capture_started",
  "push_capture_audio",
  "push_capture_level",
  "report_capture_error",
  "repair_data",
] as const;
